import React, { Component } from 'react';
import './App.css';
import Box from './Box';

class App extends Component {
  render() {
    return (
      <div className="box">
        <div className="full">
          <Box title="FULL TIME PROGRAM" des="FULL TIME PROGRAMFULL TIME PROGRAMFULL TIME PROGRAMFULL TIME PROGRAMFULL TIME PROGRAMFULL TIME PROGRAMFULL TIME PROGRAMFULL TIME PROGRAMFULL TIME PROGRAMFULL TIME PROGRAMFULL TIME PROGRAM"></Box>
        </div>
        <div className="part">
          <Box title="PART TIME PROGRAM" des="PART TIME PROGRAMPART TIME PROGRAMPART TIME PROGRAMPART TIME PROGRAMPART TIME PROGRAMPART TIME PROGRAMPART TIME PROGRAMPART TIME PROGRAMPART TIME PROGRAMPART TIME PROGRAMPART TIME PROGRAMPART T"></Box>
        </div>
        <div className="kids">
          <Box title="KIDS CODING PROGRAM" des="KIDS CODING PROGRAM KIDS CODING PROGRAM KIDS CODING PROGRAM KIDS CODING PROGRAMKIDS CODING PROGRAM KIDS CODING PROGRAM KIDS CODING PROGRAM"></Box>
        </div>
        <div className="summer">
          <Box title="SUMMER ACADEMY" des="SUMMER ACADEMYSUMMER ACADEMYSUMMER ACADEMYSUMMER ACADEMYSUMMER ACADEMYSUMMER ACADEMYSUMMER ACADEMYSUMMER ACADEMYSUMMER ACADEMYSUMMER ACADEMY"></Box>
        </div>
      </div>
    );
  }
}
export default App;